// <auto-generated />
using System;
using CommitCompilerShared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommitCompilerShared.Migrations
{
    [DbContext(typeof(CommitCompilerContext))]
    partial class CommitCompilerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("CommitCompilerShared.Models.BuildConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoMerge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEndProcess")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateStartProcess")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationBranch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailDestination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailDestinationSubject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailOriginPass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailOriginSender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Notification")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotificationSubjectCommit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PathDestination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ProcessTime")
                        .HasColumnType("REAL");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BuildConfigurations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
